import sys
from PySide6.QtWidgets import QApplication, QMainWindow, QGridLayout, QWidget

from app.helpers.paletteitem import ColorDisplayWidget
from app.mainwindow.ui_mainwindow import Ui_MainWindow
from qtpop import QtPop
 # generated by pyside6-uic


class MainWindow(QMainWindow):
    def __init__(self, qt_pop: QtPop):
        super().__init__()
        self.qt_pop = qt_pop
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self)
        self.setWindowTitle("My QtPop App")
        self.qt_pop.log.info("MainWindow initialized successfully.")
        self.qt_pop.data.broadcast_message("main_window_opened", True)

        self.setup_palette()


    def setup_palette(self):
        grid = QGridLayout()
        grid.setSpacing(5)
        grid.setContentsMargins(5, 5, 5, 5)
        columns = 4

        for i, (item, hex_val) in enumerate(self.qt_pop.style.colour_map().items()):
            row = i // columns
            col = i % columns
            grid.addWidget(ColorDisplayWidget(hex_val, item), row, col)

        old_layout = self.ui.palette_bottom_frame.layout()
        if old_layout is not None:
            QWidget().setLayout(old_layout)

        self.ui.palette_bottom_frame.setLayout(grid)


