import sys
from PySide6.QtWidgets import QApplication, QMainWindow

from app.mainwindow.ui_mainwindow import Ui_MainWindow
from qtpop import QtPop
 # generated by pyside6-uic


class MainWindow(QMainWindow):
    def __init__(self, qt_pop: QtPop):
        super().__init__()
        self._qt_pop = qt_pop
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self)
        self.setWindowTitle("My QtPop App")
